---
- name: Install Apache
  apt:
    name: apache2
    state: present
  notify: Restart Apache

- name: Copy Apache configuration file
  template:
    src: httpd.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Reload Apache

- name: Enable mod_rewrite
  command: a2enmod rewrite
  notify: Reload Apache

- name: Ensure Apache is running and enabled
  service:
    name: apache2
    state: started
    enabled: true
